name: Check Code

on:
  # push:
  #   branches: ["main", "dev"]
  # pull_request:
  #   branches: ["main", "dev"]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

permissions: write-all

jobs:
  check:
    name: Check Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      # - name: Upload coverage reports to Codecov
      #   uses: codecov/codecov-action@v3
      #   env:
      #     CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      #     verbose: true

      # - name: Install npm v8
      #   run: npm i -g npm@8

      # - name: Prettify code
      #   uses: creyD/prettier_action@v4.3
      #   with:
      #     prettier_options: --write "**/*.{md}" --tab-width 4 --use-tabs --no-bracket-spacing --prose-wrap preserve --end-of-line auto

      - name: CPP Linter
        uses: cpp-linter/cpp-linter-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: file
          files-changed-only: false
          thread-comments: true
          step-summary: true

      # - name: Github Commit & Push
      #   run: |
      #     git config --global user.name ${{ secrets.MY_USERNAME }}
      #     git config --global user.email ${{ secrets.MY_EMAIL }}
      #     git add .
      #     git commit -m "Prettify code"
      #     git push
